# Generated by Django 5.2 on 2025-05-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=9, unique=True)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.PositiveSmallIntegerField()),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasAsignatura',
            fields=[
                ('id_estadisticasAsignatura', models.AutoField(primary_key=True, serialize=False)),
                ('anioAcademico', models.PositiveIntegerField()),
                ('num_matriculados', models.PositiveIntegerField()),
                ('aprobados', models.PositiveIntegerField()),
                ('suspensos', models.PositiveIntegerField()),
                ('no_presentados', models.PositiveIntegerField()),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Estadísticas de asignaturas',
                'constraints': [models.UniqueConstraint(fields=('id_asignatura', 'anioAcademico'), name='PK_estadistica')],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_asignatura', 'id_usuario'), name='PK_favorito')],
            },
        ),
    ]
