# Generated by Django 5.2 on 2025-06-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='grado',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
