# Generated by Django 5.2 on 2025-05-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='nombre',
        ),
    ]
