version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tfgdb
      POSTGRES_USER: tfguser
      POSTGRES_PASSWORD: tfgpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tfguser -d tfgdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      USE_SQLITE: "false"
      POSTGRES_DB: tfgdb
      POSTGRES_USER: tfguser
      POSTGRES_PASSWORD: tfgpassword
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py poblar_bd &&
        gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
      "

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  postgres_data:

