version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py poblar_bd &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
